# Site settings
baseURL = "https://campnewlywed.com"
languageCode = "en-US"
title = "Camp Newlywed"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2023"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]

  # Add noindex meta to every page (ALSO CHECK robots.txt in static folder!!)
  noindex = true

  # Metadata for search engines and social sharing
  author = "Rebecca and Martin"
  description = "Camp Newlywed is a Unique Celebration."

  # Favicon
  favicon = "favicon.ico"

  [params.custom.css]
    enable = true

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links

# Links List #1 (Column 1)
[[params.links.list1]]
  heading = "Camp 101"

  [[params.links.list1.link]]
    text = "Camp Louise"
    url = "camp-louise" # Placeholder link

  [[params.links.list1.link]]
    text = "Getting Here"
    url = "directions" # Placeholder link

  [[params.links.list1.link]]
    text = "Accommodations"
    url = "accomodations" # Placeholder link

# Links List #2 (Column 2)
[[params.links.list2]]
  heading = "The Big Event"

  [[params.links.list2.link]]
    text = "Schedule of Activities"
    url = "schedule" # Placeholder link

  [[params.links.list2.link]]
    text = "Wedding Details"
    url = "details" # Placeholder link

  [[params.links.list2.link]]
    text = "RSVP"
    url = "rsvp" # Placeholder link

# Links List #3 (Column 3)
[[params.links.list3]]
  heading = "About Us"

  [[params.links.list3.link]]
    text = "Wedding Party"
    url = "wedding-party" # Placeholder link

  [[params.links.list3.link]]
    text = "The Daisies"
    url = "the-daisies" # Placeholder link

  [[params.links.list3.link]]
    text = "Registry"
    url = "registry" # Placeholder link

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
